export const defaultChartOfAccounts = [
  { account_code: '101000', account_name: 'Cash & Cash Equivalents (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '101100', account_name: 'Cash at Bank - Main Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101110', account_name: 'Cash at Bank - Operations Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101120', account_name: 'Cash at Bank - Sales Collection Account', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101130', account_name: 'Cash at Hand - Head Office', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101140', account_name: 'Cash at Hand - Factory', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '101150', account_name: 'Cash at Hand - Depot Branches', account_type: 'Asset', system_role: null, parent_account_code: '101000', is_control_account: false, is_active: true },
  { account_code: '102000', account_name: 'Accounts Receivable (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '102100', account_name: 'Trade Receivables - Customers', account_type: 'Asset', system_role: 'ACCOUNTS_RECEIVABLE', parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102200', account_name: 'Staff Debtors', account_type: 'Asset', system_role: null, parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102300', account_name: 'Other Receivables', account_type: 'Asset', system_role: null, parent_account_code: '102000', is_control_account: false, is_active: true },
  { account_code: '102400', account_name: 'Prepayments (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '102410', account_name: 'Prepayments - Insurance', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '102420', account_name: 'Prepayments - Rent', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '102430', account_name: 'Prepayments - Other', account_type: 'Asset', system_role: null, parent_account_code: '102400', is_control_account: false, is_active: true },
  { account_code: '103000', account_name: 'Inventory Control (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '103100', account_name: 'Inventory - PET Preforms (Raw Material)', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103101', account_name: 'Inventory - Master Batch (Colouring Agent)', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103102', account_name: 'Inventory - Bottle Caps', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103103', account_name: 'Inventory - Labels (75cl)', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103104', account_name: 'Inventory - Labels (50cl)', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103105', account_name: 'Inventory - Labels (33cl)', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103106', account_name: 'Inventory - Shrink Wrap 70μ', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103107', account_name: 'Inventory - Shrink Wrap 60μ', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103108', account_name: 'Inventory - Gum/Glue', account_type: 'Asset', system_role: 'INVENTORY_RAW_MATERIAL', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103110', account_name: 'Inventory - Spare Parts & Consumables', account_type: 'Asset', system_role: 'INVENTORY_CONSUMABLES', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103200', account_name: 'Inventory - Work-in-Progress', account_type: 'Asset', system_role: 'INVENTORY_WIP', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103300', account_name: 'Inventory - Finished Goods (75cl x12)', account_type: 'Asset', system_role: 'INVENTORY_FINISHED_GOODS', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103301', account_name: 'Inventory - Finished Goods (50cl x12)', account_type: 'Asset', system_role: 'INVENTORY_FINISHED_GOODS', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103302', account_name: 'Inventory - Finished Goods (50cl x20)', account_type: 'Asset', system_role: 'INVENTORY_FINISHED_GOODS', parent_account_code: '103000', is_control_account: true, is_active: true },
  { account_code: '103303', account_name: 'Inventory - Finished Goods (33cl x20)', account_type: 'Asset', system_role: 'INVENTORY_FINISHED_GOODS', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '103310', account_name: 'Inventory - Packaging Materials', account_type: 'Asset', system_role: 'INVENTORY_PACKAGING', parent_account_code: '103000', is_control_account: false, is_active: true },
  { account_code: '104000', account_name: 'Property Plant & Equipment (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '104100', account_name: 'Land', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104200', account_name: 'Buildings', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104300', account_name: 'Preform Machine', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104301', account_name: 'Blower Machine', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104302', account_name: 'Molds', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104303', account_name: 'Production Line', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104304', account_name: '75cl Label Cylinder', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104305', account_name: 'Generating Set', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104306', account_name: 'Cooling Tower', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104400', account_name: 'Motor Vehicles', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104500', account_name: 'Office Equipment', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104600', account_name: 'Furniture & Fixtures', account_type: 'Asset', system_role: null, parent_account_code: '104000', is_control_account: false, is_active: true },
  { account_code: '104700', account_name: 'Capital Work-in-Progress (CWIP)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '105200', account_name: 'Accumulated Depreciation (AUTO)', account_type: 'Asset', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '105210', account_name: 'Accum. Dep. - Preform Machine', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105211', account_name: 'Accum. Dep. - Blower Machine', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105212', account_name: 'Accum. Dep. - Molds', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: true, is_active: true },
  { account_code: '105213', account_name: 'Accum. Dep. - 75cl Label Cylinder', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105214', account_name: 'Accum. Dep. - Generating Set', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '105215', account_name: 'Accum. Dep. - Cooling Tower', account_type: 'Asset', system_role: null, parent_account_code: '105200', is_control_account: false, is_active: true },
  { account_code: '201000', account_name: 'Accounts Payable (AUTO)', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '201100', account_name: 'Trade Creditors - Suppliers', account_type: 'Liability', system_role: 'accounts_payable', parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201200', account_name: 'Accrued Expenses', account_type: 'Liability', system_role: null, parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201300', account_name: 'Payroll Payables', account_type: 'Liability', system_role: null, parent_account_code: '201000', is_control_account: false, is_active: true },
  { account_code: '201400', account_name: 'Statutory Payables (AUTO)', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '201410', account_name: 'VAT Output Payable', account_type: 'Liability', system_role: 'VAT_PAYABLE', parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201420', account_name: 'PAYE Tax Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201430', account_name: 'Withholding Tax Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201440', account_name: 'Pension Payable', account_type: 'Liability', system_role: null, parent_account_code: '201400', is_control_account: false, is_active: true },
  { account_code: '201500', account_name: 'Short-Term Loan - Bank OD', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '201600', account_name: 'Long-Term Loan - Bank', account_type: 'Liability', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '301000', account_name: 'Share Capital', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '302000', account_name: 'Retained Earnings', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '303000', account_name: 'Current Year Earnings', account_type: 'Equity', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '304000', account_name: 'Opening Balance Equity', account_type: 'Equity', system_role: 'OPENING_EQUITY', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '401000', account_name: 'Sales - 75cl x12 Pack', account_type: 'Revenue', system_role: 'SALES_REVENUE', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '401001', account_name: 'Sales - 50cl x12 Pack', account_type: 'Revenue', system_role: 'SALES_REVENUE', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '401002', account_name: 'Sales - 50cl x20 Pack', account_type: 'Revenue', system_role: 'SALES_REVENUE', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '401003', account_name: 'Sales - 33cl x20 Pack', account_type: 'Revenue', system_role: 'SALES_REVENUE', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '402000', account_name: 'Sales Returns & Allowances', account_type: 'Revenue', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '403000', account_name: 'Other Income', account_type: 'Revenue', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '501000', account_name: 'Cost of Goods Sold - 75cl x12', account_type: 'COGS', system_role: 'COGS', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '501001', account_name: 'Cost of Goods Sold - 50cl x12', account_type: 'COGS', system_role: 'COGS', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '501002', account_name: 'Cost of Goods Sold - 50cl x20', account_type: 'COGS', system_role: 'COGS', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '501003', account_name: 'Cost of Goods Sold - 33cl x20', account_type: 'COGS', system_role: 'COGS', parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '502000', account_name: 'Salaries and Wages - Production', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '502100', account_name: 'Salaries and Wages - Admin', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '503000', account_name: 'Rent Expense', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '504000', account_name: 'Electricity - Production', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '504100', account_name: 'Electricity - Admin General', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '505000', account_name: 'Marketing Expenses', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506000', account_name: 'Depreciation Expense - Preform Machine', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '506001', account_name: 'Depreciation Expense - Blower', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506002', account_name: 'Depreciation Expense - Molds', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506003', account_name: 'Depreciation Expense - 75cl Label Cylinder', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: true, is_active: true },
  { account_code: '506004', account_name: 'Depreciation Expense - 50cl Label Cylinder', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506005', account_name: 'Depreciation Expense - 33cl Label Cylinder', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506006', account_name: 'Depreciation Expense - Generating Set', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '506007', account_name: 'Depreciation Expense - Cooling Tower', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '507000', account_name: 'Bank Charges', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '508000', account_name: 'Insurance Expense', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '509000', account_name: 'Maintenance Materials', account_type: 'Expense', system_role: null, parent_account_code: null, is_control_account: false, is_active: true },
  { account_code: '509100', account_name: 'Maintenance - Cottol Wool', account_type: 'Expense', system_role: null, parent_account_code: '509000', is_control_account: false, is_active: true },
  { account_code: '509200', account_name: 'Maintenance - Thinner (5L)', account_type: 'Expense', system_role: null, parent_account_code: '509000', is_control_account: false, is_active: true },
  { account_code: '509300', account_name: 'Maintenance - Ethanol (10L)', account_type: 'Expense', system_role: null, parent_account_code: '509000', is_control_account: false, is_active: true },
  { account_code: '509400', account_name: 'Maintenance - Soaps Cleaners', account_type: 'Expense', system_role: null, parent_account_code: '509000', is_control_account: false, is_active: true },
  { account_code: '599999', account_name: 'Miscellaneous Expenses', account_type: 'Expense', system_role: 'default_expense', parent_account_code: null, is_control_account: false, is_active: true },
];

export const defaultInventoryCategoryMap = [
  { category_name: 'Consumables & Production Supplies', system_role: 'INVENTORY_CONSUMABLES' },
  { category_name: 'Finished Goods Inventory', system_role: 'INVENTORY_FINISHED_GOODS' },
  { category_name: 'Fuel & Energy Inventory', system_role: 'INVENTORY_FUEL' },
  { category_name: 'Goods-in-Transit Inventory', system_role: 'INVENTORY_TRANSIT' },
  { category_name: 'Obsolete, Expired & Scrap Inventory', system_role: 'INVENTORY_SCRAP' },
  { category_name: 'Packaging Materials Inventory', system_role: 'INVENTORY_PACKAGING' },
  { category_name: 'Promotional & Marketing Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Raw Materials Inventory', system_role: 'INVENTORY_RAW_MATERIAL' },
  { category_name: 'Rejected / Quality-Hold Inventory', system_role: 'INVENTORY_QUALITY' },
  { category_name: 'Returned Goods / Reverse Inventory', system_role: 'INVENTORY_RETURNED' },
  { category_name: 'Safety Stock / Buffer Inventory', system_role: 'INVENTORY_SAFETY' },
  { category_name: 'Spare Parts & Maintenance Inventory', system_role: 'INVENTORY_CONSUMABLES' },
  { category_name: 'Third-Party / Consignment Inventory', system_role: 'INVENTORY_OTHER' },
  { category_name: 'Work-in-Progress (WIP) Inventory', system_role: 'INVENTORY_WIP' },
];
